<#
.SYNOPSIS
  One-shot build for TechToolbox:
  - Update manifest (version & GUID)
  - (Optional) Run PSSA analysis
  - Sign module files
  - (Optional) Package artifacts
    - (Optional) Release automation (bump/commit/tag/push)

.NOTES
  - Prefers PS7+ but works on Windows PowerShell 5.1+
  - Non-interactive by default; prompts only with -Interactive
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [switch]$AutoVersionPatch,
    [switch]$ReleaseTechToolbox,
    [switch]$ReleaseTechAgent,
    [switch]$ReleaseTechShell,
    [switch]$RegenerateGuid,
    [switch]$SkipSigning,
    [bool]$SkipValidSigs = $true,
    [switch]$Recurse,
    [switch]$Analyze,         # Run PSSA (PowerShell ScriptAnalyzer)
    [switch]$FailOnPssa,      # Fail build if PSSA finds issues
    [switch]$SkipProjects,    # Skip .NET project build/publish steps
    [switch]$BuildTechShellWinget, # Opt-in: build/sign TechShell MSIX + winget manifests via Config\Build-TechShellWinget.ps1
    [string]$Version,          # Override the TechShell package version generated by the winget/MSIX bundle when needed.
    [switch]$SkipTechShell,    # Explicitly disable TechShell build/publish even when release or caller opts in
    [string]$TechShellReleaseTag,
    [ValidateSet('win-x64', 'win-x86', 'win-arm64')]
    [string]$TechShellRuntimeIdentifier = 'win-x64',
    [string]$TechShellInstallerFileName = 'TechShell.msix',
    [switch]$SkipTechShellManifestWrite,
    [switch]$SkipTechShellManifestValidation,
    [switch]$ExportPublic,    # Export only functions discovered in Public\ (else '*')
    [switch]$Pack,            # Zip to .\Out\TechToolbox_<version>.zip
    [switch]$Interactive,     # Allow prompts when data is missing
    [string]$ModuleRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$ConfigPath,
    [string]$TimestampServer,
    [string]$Thumbprint
)

function Invoke-Git {
    param(
        [Parameter(Mandatory)]
        [string[]]$gitArgs,
        [switch]$IgnoreExitCode
    )

    $output = & git -C $ModuleRoot @gitArgs 2>&1
    if ($LASTEXITCODE -ne 0 -and -not $IgnoreExitCode) {
        $joined = ($output | Out-String).Trim()
        throw "git $($gitArgs -join ' ') failed: $joined"
    }

    return ($output | Out-String).Trim()
}

function Resolve-DotNetInvocation {
    $sdkScopedPattern = '[\\/]sdk[\\/][^\\/]+[\\/]dotnet(?:\.exe)?$'
    $dotnetHost = $null

    $resolved = Get-Command dotnet -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($resolved) {
        $resolvedPath = [string]$resolved.Source
        if ([string]::IsNullOrWhiteSpace($resolvedPath)) {
            $resolvedPath = [string]$resolved.Path
        }

        if (-not [string]::IsNullOrWhiteSpace($resolvedPath) -and $resolvedPath -notmatch $sdkScopedPattern) {
            $dotnetHost = $resolvedPath
        }
    }

    $fallbackCandidates = @()
    if (-not [string]::IsNullOrWhiteSpace($env:DOTNET_ROOT)) {
        $fallbackCandidates += (Join-Path $env:DOTNET_ROOT 'dotnet.exe')
    }
    if (-not [string]::IsNullOrWhiteSpace($env:ProgramFiles)) {
        $fallbackCandidates += (Join-Path $env:ProgramFiles 'dotnet\dotnet.exe')
    }

    foreach ($candidate in ($fallbackCandidates | Select-Object -Unique)) {
        if (-not [string]::IsNullOrWhiteSpace($candidate) -and (Test-Path -LiteralPath $candidate -PathType Leaf)) {
            $dotnetHost = $candidate
            break
        }
    }

    if ([string]::IsNullOrWhiteSpace($dotnetHost)) {
        if ($resolved) {
            $resolvedPathForError = [string]$resolved.Source
            if ([string]::IsNullOrWhiteSpace($resolvedPathForError)) {
                $resolvedPathForError = [string]$resolved.Path
            }

            if ($resolvedPathForError -match $sdkScopedPattern) {
                throw "Resolved 'dotnet' to SDK-scoped host path '$resolvedPathForError', which is invalid. Ensure a valid .NET host is available at DOTNET_ROOT\dotnet.exe or Program Files\dotnet\dotnet.exe."
            }
        }

        throw ".NET host executable 'dotnet' could not be resolved. Install/repair .NET SDK and ensure dotnet.exe is available."
    }

    $versionOutput = & $dotnetHost --version 2>&1
    if ($LASTEXITCODE -eq 0) {
        return [pscustomobject]@{
            HostPath       = $dotnetHost
            Prefix         = @()
            DisplayCommand = $dotnetHost
        }
    }

    $listSdkOutput = & $dotnetHost --list-sdks 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw ".NET host '$dotnetHost' failed --version and --list-sdks checks. --version output: $($versionOutput -join [Environment]::NewLine)"
    }

    $sdkCandidates = @()
    foreach ($sdkLine in $listSdkOutput) {
        if ($sdkLine -match '^\s*([0-9]+\.[0-9]+\.[0-9]+)\s+\[(.+)\]\s*$') {
            $sdkVersionText = $matches[1]
            $sdkRoot = $matches[2]
            $sdkDotNetDll = Join-Path (Join-Path $sdkRoot $sdkVersionText) 'dotnet.dll'
            if (Test-Path -LiteralPath $sdkDotNetDll -PathType Leaf) {
                $sdkCandidates += [pscustomobject]@{
                    Version    = [version]$sdkVersionText
                    VersionRaw = $sdkVersionText
                    DotNetDll  = $sdkDotNetDll
                }
            }
        }
    }

    foreach ($sdkCandidate in ($sdkCandidates | Sort-Object Version -Descending)) {
        & $dotnetHost exec $sdkCandidate.DotNetDll --version *> $null
        if ($LASTEXITCODE -eq 0) {
            return [pscustomobject]@{
                HostPath       = $dotnetHost
                Prefix         = @('exec', $sdkCandidate.DotNetDll)
                DisplayCommand = "$dotnetHost exec $($sdkCandidate.DotNetDll)"
            }
        }
    }

    throw ".NET host '$dotnetHost' is present but could not execute any installed SDK command host. --version output: $($versionOutput -join [Environment]::NewLine)"
}

# ---------------- 01. Load config --------------------------------------------
$defaultConfigDir = Join-Path $ModuleRoot 'Config'
$defaultConfigPath = Join-Path $defaultConfigDir 'build.config.json'
$legacyConfigPath = Join-Path $ModuleRoot 'build.config.json'

if ([string]::IsNullOrWhiteSpace($ConfigPath)) {
    if (Test-Path -LiteralPath $defaultConfigPath) {
        $ConfigPath = $defaultConfigPath
    }
    elseif (Test-Path -LiteralPath $legacyConfigPath) {
        Write-Warning "Legacy build config found at '$legacyConfigPath'. Move it to '$defaultConfigPath'."
        $ConfigPath = $legacyConfigPath
    }
    else {
        $ConfigPath = $defaultConfigPath
    }
}
elseif (-not [System.IO.Path]::IsPathRooted($ConfigPath)) {
    $ConfigPath = Join-Path $ModuleRoot $ConfigPath
}

$cfg = $null
if (Test-Path -LiteralPath $ConfigPath) {
    $cfg = Get-Content -Raw -LiteralPath $ConfigPath | ConvertFrom-Json
}
else {
    throw "Build config not found at '$ConfigPath'. Expected '$defaultConfigPath' or a valid override path."
}

$TimestampServer = $cfg.signing.timestamp ?? 'http://timestamp.digicert.com'
$Thumbprint = $cfg.signing.thumbprint

$rawOutDir = if ($null -ne $cfg.artifacts -and $null -ne $cfg.artifacts.outDir) { [string]$cfg.artifacts.outDir } else { '.\Out' }
$outDir = if ([System.IO.Path]::IsPathRooted($rawOutDir)) { $rawOutDir } else { Join-Path $ModuleRoot $rawOutDir }

$rawPssaSettings = if ($null -ne $cfg.quality -and $null -ne $cfg.quality.pssaSettings) { [string]$cfg.quality.pssaSettings } else { '.\PSScriptAnalyzerSettings.psd1' }
$pssaSettings = if ([System.IO.Path]::IsPathRooted($rawPssaSettings)) { $rawPssaSettings } else { Join-Path $ModuleRoot $rawPssaSettings }

$analyzeEnabled = $Analyze.IsPresent -or ($cfg.quality.analyze -eq $true)
$failOnPssa = $FailOnPssa.IsPresent -or ($cfg.quality.failOnPssa -eq $true)

$releaseSwitches = @($ReleaseTechToolbox, $ReleaseTechAgent, $ReleaseTechShell) | Where-Object { $_ -is [bool] -and $_ }
if ($releaseSwitches.Count -gt 1) {
    throw "Use only one release switch at a time: -ReleaseTechToolbox, -ReleaseTechAgent, or -ReleaseTechShell."
}

if ($ReleaseTechShell -and $BuildTechShellWinget) {
    throw "Use -ReleaseTechShell by itself. Do not combine it with -BuildTechShellWinget."
}

if ($ReleaseTechToolbox -and $BuildTechShellWinget) {
    throw "Use -ReleaseTechToolbox for the module release path. For TechShell packaging, run -ReleaseTechShell or call the bundle script directly."
}

if ($ReleaseTechAgent -and $BuildTechShellWinget) {
    throw "Use -ReleaseTechAgent for the runtime release path. Do not combine it with -BuildTechShellWinget."
}

if ($ReleaseTechShell) {
    $BuildTechShellWinget = $true
}

$isReleaseTechToolbox = $ReleaseTechToolbox
$isReleaseTechAgent = $ReleaseTechAgent
$isReleaseTechShell = $ReleaseTechShell

# Release mode implies patch bump + manifest update flow, then git commit/tag/push.
if ($isReleaseTechToolbox -or $isReleaseTechAgent) {
    if ($isReleaseTechToolbox) {
        $AutoVersionPatch = $true
    }

    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw "git is required for release mode but was not found in PATH."
    }

    $repoRoot = Invoke-Git -gitArgs @('rev-parse', '--show-toplevel')
    if (-not $repoRoot) {
        throw "Release mode requires running inside a git repository."
    }

    $preReleaseDirty = Invoke-Git -gitArgs @('status', '--porcelain')
    if (-not [string]::IsNullOrWhiteSpace($preReleaseDirty)) {
        throw "Working tree is not clean. Commit or stash local changes before running a release."
    }

    $releaseBranch = Invoke-Git -gitArgs @('rev-parse', '--abbrev-ref', 'HEAD')
    if ([string]::Equals($releaseBranch, 'HEAD', [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Release mode requires a named branch checkout (detached HEAD is not supported for release pushes)."
    }

    Invoke-Git -gitArgs @('fetch', 'origin', $releaseBranch) | Out-Null
    $behindRaw = Invoke-Git -gitArgs @('rev-list', '--count', "HEAD..origin/$releaseBranch")
    $behindCount = 0
    [void][int]::TryParse($behindRaw, [ref]$behindCount)
    if ($behindCount -gt 0) {
        Write-Host "Release branch '$releaseBranch' is behind origin by $behindCount commit(s); rebasing before release." -ForegroundColor Yellow
        Invoke-Git -gitArgs @('pull', '--rebase', 'origin', $releaseBranch) | Out-Null
    }

    if ($isReleaseTechToolbox) {
        Write-Host "TechToolbox release mode enabled: auto-version patch + manifest update + git release steps." -ForegroundColor Cyan
    }
    else {
        Write-Host "TechAgent release mode enabled: git tag + release push using the provided version tag." -ForegroundColor Cyan
    }
}

# ---------------- 02. Validate environment -----------------------------------
$manifestPath = Join-Path $ModuleRoot 'TechToolbox.psd1'
if (-not (Test-Path -LiteralPath $manifestPath)) {
    throw "Manifest not found: $manifestPath"
}

# ---------------- Helper: Import manifest ------------------------------------
$manifest = Import-PowerShellDataFile -Path $manifestPath
$manifestDescription = [string]$manifest.Description
$manifestReleaseNotes = [string]$manifest.PrivateData.PSData.ReleaseNotes
$manifestPowerShellVersion = '7.4.0'

# ---------------- 03. Compute new values -------------------------------------
$oldGuid = $manifest.Guid
$newGuid = if ($RegenerateGuid) { [guid]::NewGuid().Guid } else { $oldGuid }

$oldVersion = [version]$manifest.ModuleVersion
$newVersion = if ($AutoVersionPatch) {
    $build = if ($oldVersion.Build -ge 0) { $oldVersion.Build } else { 0 }
    [version]::new($oldVersion.Major, $oldVersion.Minor, $build + 1)
}
else { $oldVersion }

if ($Version -and $isReleaseTechToolbox) {
    $newVersion = [version]$Version
}

# Paths
$publicFolder = Join-Path $ModuleRoot 'Public'
$manifestPath = Join-Path $ModuleRoot 'TechToolbox.psd1'

# Collect public function names from file basenames
$publicFiles = Get-ChildItem -LiteralPath $publicFolder -Filter *.ps1 -File -Recurse
$publicFuns = $publicFiles.BaseName | Sort-Object -Unique

# Preserve explicit non-Public exports (wrappers/entry points in .psm1)
$nonPublicExports = @()

$mergedExports = @($publicFuns + $nonPublicExports) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique

# Fall back to '*' only if nothing found (e.g., dev shell without Public yet)
$functionsToExport = if ($mergedExports.Count -gt 0) { $mergedExports } else { @('*') }

# Keep aliases explicit (avoid '*') for faster module analysis
$aliasesToExport = @()  # set to concrete alias names when you have them

# Preserve existing PrivateData (both top-level keys and PSData)
$privateData = [ordered]@{}
if ($manifest.PrivateData) {
    $privateData = [ordered]@{} + $manifest.PrivateData
}

$psdata = [ordered]@{}
if ($privateData.PSData) {
    $psdata = [ordered]@{} + $privateData.PSData
}

# Normalize tags so gallery metadata remains valid (example: "active directory" -> "active-directory" then filter both deprecated forms).
if (($psdata.Keys -contains 'Tags') -and $null -ne $psdata.Tags) {
    $deprecatedTags = @('active-directory', 'active directory')

    $normalizedTags = @(
        $psdata.Tags | ForEach-Object {
            if ($_ -is [string]) {
                ($_ -replace '\s+', '-').Trim('-')
            }
            else {
                $_
            }
        }
    ) | Where-Object {
        -not [string]::IsNullOrWhiteSpace([string]$_) -and
        ($deprecatedTags -notcontains [string]$_)
    } | Select-Object -Unique

    $psdata['Tags'] = $normalizedTags
}

# Rebuild full PrivateData with normalized PSData
$privateData['PSData'] = $psdata

# Update manifest once (both exports and PrivateData)
Update-ModuleManifest -Path $manifestPath `
    -FunctionsToExport $functionsToExport `
    -AliasesToExport   $aliasesToExport `
    -Description       $manifestDescription `
    -ReleaseNotes      $manifestReleaseNotes `
    -PowerShellVersion $manifestPowerShellVersion `
    -PrivateData       $privateData

# ---------------- 04. Dirty check & update manifest --------------------------
$manifestChanged = $false
$exportsChanged = ($manifest.FunctionsToExport -join ',') -ne ($functionsToExport -join ',')

if ($oldGuid -ne $newGuid -or $oldVersion -ne $newVersion -or $exportsChanged) {
    if ($PSCmdlet.ShouldProcess($manifestPath, "Update manifest")) {
        Update-ModuleManifest -Path $manifestPath `
            -ModuleVersion $newVersion `
            -Guid $newGuid `
            -FunctionsToExport $functionsToExport `
            -AliasesToExport   $aliasesToExport `
            -Description       $manifestDescription `
            -ReleaseNotes      $manifestReleaseNotes `
            -PowerShellVersion $manifestPowerShellVersion `
            -PrivateData $privateData
        $manifestChanged = $true
        Write-Host "Manifest updated → Version: $oldVersion → $newVersion; Guid: $oldGuid → $newGuid" -ForegroundColor Cyan
    }
}
else {
    Write-Host "Manifest unchanged (no updates needed)." -ForegroundColor DarkCyan
}

# ---------------- 05. (Optional) PSSA analysis --------------------------------
$pssaIssues = @()
if ($analyzeEnabled) {
    try {
        if (-not (Get-Module -ListAvailable -Name PSScriptAnalyzer)) {
            Write-Warning "PSScriptAnalyzer module not found. Skipping analysis."
        }
        else {
            Import-Module PSScriptAnalyzer -ErrorAction Stop
            Write-Host "Running PSSA (ScriptAnalyzer)..." -ForegroundColor Cyan
            $pssaIssues = Invoke-ScriptAnalyzer -Path $ModuleRoot `
                -Settings $pssaSettings -Recurse
            if ($pssaIssues.Count -gt 0) {
                # Store a machine-readable report under CodeAnalysis\
                $caDir = Join-Path $ModuleRoot 'CodeAnalysis'
                New-Item -ItemType Directory -Force -Path $caDir | Out-Null
                $reportPath = Join-Path $caDir ("PSSA-Report_{0:yyyyMMdd_HHmmss}.json" -f (Get-Date))
                $pssaIssues | ConvertTo-Json -Depth 6 | Out-File -LiteralPath $reportPath -Encoding UTF8
                Write-Host "PSSA found $($pssaIssues.Count) issue(s). Report: $reportPath" -ForegroundColor Yellow
                if ($failOnPssa -and -not $Interactive) {
                    throw "Build failed due to ScriptAnalyzer findings."
                }
            }
            else {
                Write-Host "PSSA clean." -ForegroundColor Green
            }
        }
    }
    catch {
        throw "PSSA run failed: $($_.Exception.Message)"
    }
}

# ---------------- 06. Signing -------------------------------------------------
function Get-CodeSigningCert {
    param([Parameter(Mandatory)] [string]$Thumb)
    $stores = @('Cert:\CurrentUser\My', 'Cert:\LocalMachine\My')
    foreach ($store in $stores) {
        $found = Get-ChildItem $store -ErrorAction SilentlyContinue |
        Where-Object { $_.Thumbprint -eq $Thumb }
        if ($found -and $found.HasPrivateKey) { return $found }
    }
    return $null
}

function Test-CodeSigningTrustPreflight {
    param(
        [Parameter(Mandatory)] [System.Security.Cryptography.X509Certificates.X509Certificate2]$Certificate
    )

    $chain = New-Object System.Security.Cryptography.X509Certificates.X509Chain
    $chain.ChainPolicy.RevocationMode = [System.Security.Cryptography.X509Certificates.X509RevocationMode]::NoCheck
    $chain.ChainPolicy.VerificationFlags = [System.Security.Cryptography.X509Certificates.X509VerificationFlags]::NoFlag

    $chainBuildSucceeded = $chain.Build($Certificate)
    $statuses = @($chain.ChainStatus | ForEach-Object { $_.Status.ToString() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique)
    $isSelfSigned = [string]::Equals($Certificate.Subject, $Certificate.Issuer, [System.StringComparison]::OrdinalIgnoreCase)
    $hasUntrustedRoot = $statuses -contains 'UntrustedRoot'

    [pscustomobject]@{
        IsPublicTrustReady  = $chainBuildSucceeded -and -not $isSelfSigned -and -not $hasUntrustedRoot
        IsSelfSigned        = $isSelfSigned
        ChainBuildSucceeded = $chainBuildSucceeded
        ChainStatuses       = $statuses
        StatusText          = if ($statuses.Count -gt 0) { $statuses -join ', ' } else { 'None' }
    }
}

function Sign-FileSet {
    param(
        [Parameter(Mandatory)] [string[]]$Files,
        [Parameter(Mandatory)] [System.Security.Cryptography.X509Certificates.X509Certificate2]$Certificate,
        [switch]$SkipValidSigs,
        [string]$TimestampServer,
        [ref]$OkCount,
        [ref]$SkippedCount,
        [ref]$WarnCount
    )

    foreach ($f in $Files) {
        if (-not (Test-Path -LiteralPath $f)) { continue }

        try {
            if ($SkipValidSigs) {
                $sig = Get-AuthenticodeSignature -FilePath $f
                if ($sig.Status -eq 'Valid') { $SkippedCount.Value++; continue }
            }

            $params = @{
                FilePath      = $f
                Certificate   = $Certificate
                HashAlgorithm = 'SHA256'
            }
            if ($TimestampServer) { $params['TimestampServer'] = $TimestampServer }

            $r = Set-AuthenticodeSignature @params
            if ($r.Status -eq 'Valid') { $OkCount.Value++ } else { $WarnCount.Value++ }
        }
        catch {
            $WarnCount.Value++
        }
    }
}

$ok = 0; $skip = 0; $warn = 0
if ($SkipSigning) {
    Write-Host "Signing skipped (-SkipSigning)." -ForegroundColor DarkYellow
}
else {
    if (-not $Thumbprint) {
        if ($Interactive) { $Thumbprint = Read-Host "Enter code signing thumbprint" }
        else { throw "Thumbprint not provided (set Config\build.config.json signing.thumbprint or pass -Thumbprint)." }
    }
    $cert = Get-CodeSigningCert -Thumb $Thumbprint
    if (-not $cert) { throw "Code signing cert not found or missing private key for thumbprint $Thumbprint." }
    $trustPreflight = Test-CodeSigningTrustPreflight -Certificate $cert
    if (-not $trustPreflight.IsPublicTrustReady) {
        throw "Code-signing trust preflight detected a non-public trust chain for thumbprint $Thumbprint. SelfSigned=$($trustPreflight.IsSelfSigned); ChainBuildSucceeded=$($trustPreflight.ChainBuildSucceeded); ChainStatuses=$($trustPreflight.StatusText). Use a publicly trusted code-signing certificate."
    }
    Write-Host "Code-signing trust preflight passed for thumbprint $Thumbprint." -ForegroundColor Green

    # What to sign
    $search = @{ Path = $ModuleRoot; Include = '*.ps1', '*.psm1'; File = $true; Recurse = $true }
    $files = Get-ChildItem @search | Where-Object {
        $_.FullName -notmatch '\\(Out|Bin|CodeAnalysis|\.git)\\'
    }

    Write-Host "Signing $(($files|Measure-Object).Count) file(s)..." -ForegroundColor Cyan
    Sign-FileSet -Files ($files.FullName) -Certificate $cert -SkipValidSigs:$SkipValidSigs -TimestampServer $TimestampServer -OkCount ([ref]$ok) -SkippedCount ([ref]$skip) -WarnCount ([ref]$warn)
    Write-Host "Signing complete → OK: $ok  Skipped: $skip  Warnings/Errors: $warn" -ForegroundColor Cyan
}

# ---------------- 06A. Build + publish .NET agent projects ------------------
if ($SkipProjects) {
    Write-Host "Skipping .NET project build/publish (-SkipProjects)." -ForegroundColor DarkYellow
}
else {
    $dotnetInvocation = Resolve-DotNetInvocation
    $dotnetExe = $dotnetInvocation.HostPath
    $dotnetPrefix = @($dotnetInvocation.Prefix)
    Write-Host "Using dotnet command: $($dotnetInvocation.DisplayCommand)" -ForegroundColor DarkGray

    $dotNetProjects = @(
        [pscustomobject]@{
            Name        = 'TechToolbox.Agent'
            ProjectPath = Join-Path $ModuleRoot 'src\TechToolbox.Agent\TechToolbox.Agent.csproj'
            PublishDir  = Join-Path $ModuleRoot 'src\TechToolbox.Agent\bin\Release\net8.0\publish'
            Publish     = $true
        },
        [pscustomobject]@{
            Name        = 'TechToolbox.LocalMcpAdapter'
            ProjectPath = Join-Path $ModuleRoot 'src\TechToolbox.Agent\TechToolbox.LocalMcpAdapter\TechToolbox.LocalMcpAdapter.csproj'
            PublishDir  = Join-Path $ModuleRoot 'src\TechToolbox.Agent\TechToolbox.LocalMcpAdapter\bin\Release\net8.0\publish'
            Publish     = $true
        },
        [pscustomobject]@{
            Name        = 'TechShell.UI'
            ProjectPath = Join-Path $ModuleRoot 'src\TechShell\src\TechShell.UI\TechShell.UI.csproj'
            PublishDir  = $null
            Publish     = $false
        }
    )

    foreach ($project in $dotNetProjects) {
        if (-not (Test-Path -LiteralPath $project.ProjectPath)) {
            Write-Host "Skipping .NET build/publish for missing project: $($project.ProjectPath)" -ForegroundColor DarkYellow
            continue
        }

        Write-Host "Building .NET project: $($project.Name)" -ForegroundColor Cyan
        & $dotnetExe @dotnetPrefix build $project.ProjectPath -c Release
        if ($LASTEXITCODE -ne 0) {
            throw "dotnet build failed for $($project.ProjectPath)"
        }

        if ($project.Publish) {
            if (Test-Path -LiteralPath $project.PublishDir) {
                Remove-Item -LiteralPath $project.PublishDir -Recurse -Force
            }

            $publishArgs = @('publish', $project.ProjectPath, '-c', 'Release', '-o', $project.PublishDir)

            Write-Host "Publishing .NET project: $($project.Name)" -ForegroundColor Cyan
            & $dotnetExe @dotnetPrefix @publishArgs
            if ($LASTEXITCODE -ne 0) {
                throw "dotnet publish failed for $($project.ProjectPath)"
            }

            if (-not $SkipSigning) {
                $publishExes = @(Get-ChildItem -LiteralPath $project.PublishDir -Filter *.exe -File -Recurse | Select-Object -ExpandProperty FullName)
                if ($publishExes.Count -gt 0) {
                    Write-Host "Signing published EXE(s) for $($project.Name): $(($publishExes | Measure-Object).Count) file(s)" -ForegroundColor Cyan
                    Sign-FileSet -Files $publishExes -Certificate $cert -SkipValidSigs:$SkipValidSigs -TimestampServer $TimestampServer -OkCount ([ref]$ok) -SkippedCount ([ref]$skip) -WarnCount ([ref]$warn)
                }
            }

            Write-Host "Build + publish complete for $($project.Name) → $($project.PublishDir)" -ForegroundColor Green
        }
        else {
            Write-Host "Build complete for $($project.Name) (publish skipped by policy)." -ForegroundColor Green
        }
    }
}

# ---------------- 06B. (Optional) Build TechShell winget bundle -------------
$techShellWingetResult = $null
if ($BuildTechShellWinget -and -not $SkipTechShell) {
    if ($SkipSigning) {
        throw "TechShell winget build requires signing; remove -SkipSigning or disable -BuildTechShellWinget."
    }

    $techShellWingetScript = Join-Path $defaultConfigDir 'Build-TechShellWinget.ps1'
    if (-not (Test-Path -LiteralPath $techShellWingetScript -PathType Leaf)) {
        throw "TechShell winget build script not found: $techShellWingetScript"
    }

    $techShellPackageVersion = if ([string]::IsNullOrWhiteSpace($Version)) { $newVersion.ToString() } else { $Version }
    $resolvedTechShellTag = if ([string]::IsNullOrWhiteSpace($TechShellReleaseTag)) { "v$techShellPackageVersion" } else { $TechShellReleaseTag }
    $techShellArgs = @{
        PackageVersion         = $techShellPackageVersion
        ReleaseTag             = $resolvedTechShellTag
        RuntimeIdentifier      = $TechShellRuntimeIdentifier
        InstallerFileName      = $TechShellInstallerFileName
        Thumbprint             = $Thumbprint
        TimestampServer        = $TimestampServer
        SkipManifestWrite      = $SkipTechShellManifestWrite
        SkipManifestValidation = $SkipTechShellManifestValidation
    }

    Write-Host "Building TechShell winget bundle for version $($newVersion.ToString()) (tag $resolvedTechShellTag)..." -ForegroundColor Cyan
    $techShellWingetResult = & $techShellWingetScript @techShellArgs
    Write-Host "TechShell winget build complete." -ForegroundColor Green
}

# ---------------- 07. (Optional) Package -------------------------------------
$artifact = $null
if ($Pack) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
    $zip = Join-Path $outDir ("TechToolbox_{0}.zip" -f $newVersion)
    if (Test-Path $zip) { Remove-Item $zip -Force }
    # Zip only module assets
    $items = @(
        (Join-Path $ModuleRoot 'TechToolbox.psd1'),
        (Join-Path $ModuleRoot 'TechToolbox.psm1'),
        (Join-Path $ModuleRoot 'Public\*'),
        (Join-Path $ModuleRoot 'Private\*'),
        (Join-Path $ModuleRoot 'Config\*')
    )

    Compress-Archive -Path $items -DestinationPath $zip
    $artifact = $zip
    Write-Host "Packaged → $artifact" -ForegroundColor Green
}

# ---------------- 08. (Optional) Release commit/tag/push ---------------------
$releaseTag = $null
$releaseCommit = $null
$releasePushed = $false
if ($isReleaseTechToolbox -or $isReleaseTechAgent) {
    $resolvedReleaseVersion = if ($Version) { [string]$Version } elseif ($isReleaseTechToolbox) { [string]$newVersion } else { [string]$oldVersion }
    $releaseTag = if ($isReleaseTechToolbox) { "v$resolvedReleaseVersion" } else { "agent-v$resolvedReleaseVersion" }

    $existingTag = Invoke-Git -gitArgs @('tag', '--list', $releaseTag)
    if (-not [string]::IsNullOrWhiteSpace($existingTag)) {
        throw "Tag already exists: $releaseTag"
    }

    $branchName = Invoke-Git -gitArgs @('rev-parse', '--abbrev-ref', 'HEAD')

    if ($isReleaseTechToolbox) {
        Invoke-Git -gitArgs @('add', '-A') | Out-Null
        & git -C $ModuleRoot diff --cached --quiet
        if ($LASTEXITCODE -eq 0) {
            throw "No staged changes detected after release build. Nothing to commit/tag."
        }

        $commitMessage = "release: $releaseTag"
        if ($PSCmdlet.ShouldProcess($ModuleRoot, "Create release commit ($commitMessage)")) {
            Invoke-Git -gitArgs @('commit', '-m', $commitMessage) | Out-Null
            $releaseCommit = Invoke-Git -gitArgs @('rev-parse', '--short', 'HEAD')
            Write-Host "Release commit created: $releaseCommit" -ForegroundColor Green
        }
    }

    if ($PSCmdlet.ShouldProcess($ModuleRoot, "Create git tag $releaseTag")) {
        Invoke-Git -gitArgs @('tag', '-a', $releaseTag, '-m', "Release $releaseTag") | Out-Null
        Write-Host "Tag created: $releaseTag" -ForegroundColor Green
    }

    if ($isReleaseTechToolbox) {
        if ($PSCmdlet.ShouldProcess($ModuleRoot, "Push branch '$branchName' and tag '$releaseTag' to origin")) {
            Invoke-Git -gitArgs @('push', 'origin', $branchName) | Out-Null
            Invoke-Git -gitArgs @('push', 'origin', $releaseTag) | Out-Null
            $releasePushed = $true
            Write-Host "Pushed branch + tag. Tag push should trigger .github/workflows/publish.yml" -ForegroundColor Green
        }
    }
    else {
        if ($PSCmdlet.ShouldProcess($ModuleRoot, "Push tag '$releaseTag' to origin")) {
            Invoke-Git -gitArgs @('push', 'origin', $releaseTag) | Out-Null
            $releasePushed = $true
            Write-Host "Pushed tag '$releaseTag' for the TechAgent release lane. It does not match the PSGallery v* trigger." -ForegroundColor Green
        }
    }
}

# ---------------- 09. Emit summary -------------------------------------------
$result = [pscustomobject]@{
    ManifestPath    = $manifestPath
    Version         = [pscustomobject]@{ Old = $oldVersion; New = $newVersion }
    Guid            = [pscustomobject]@{ Old = $oldGuid; New = $newGuid }
    ManifestUpdated = $manifestChanged
    PssaIssues      = $pssaIssues.Count
    FilesSigned     = $ok
    FilesSkipped    = $skip
    FilesWarned     = $warn
    ArtifactPath    = $artifact
    TechShellWinget = if ($null -ne $techShellWingetResult) {
        [pscustomobject]@{
            Enabled           = $true
            ReleaseTag        = $techShellWingetResult.ReleaseTag
            RuntimeIdentifier = $techShellWingetResult.RuntimeIdentifier
            InstallerPath     = $techShellWingetResult.InstallerPath
            ManifestWritten   = $techShellWingetResult.ManifestWritten
            ManifestValidated = $techShellWingetResult.ManifestValidated
            SigningThumbprint = $techShellWingetResult.SigningThumbprint
        }
    }
    else {
        [pscustomobject]@{ Enabled = $false }
    }
    Release         = [pscustomobject]@{
        Enabled      = [bool]($isReleaseTechToolbox -or $isReleaseTechAgent)
        TechToolbox  = [bool]$isReleaseTechToolbox
        TechAgent    = [bool]$isReleaseTechAgent
        TechShell    = [bool]$isReleaseTechShell
        Commit       = $releaseCommit
        Tag          = $releaseTag
        Pushed       = $releasePushed
        PipelineHint = if ($releasePushed -and $releaseTag) { "GitHub Actions publish workflow triggers on pushed v* tags." } else { $null }
    }
}
$result

# SIG # Begin signature block
# MIImyAYJKoZIhvcNAQcCoIImuTCCJrUCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCABOazVKODlr1Cx
# /domzRqkAa+g6JECoXK7QgFsLv0Cq6CCIFgwggWNMIIEdaADAgECAhAOmxiO+dAt
# 5+/bUOIIQBhaMA0GCSqGSIb3DQEBDAUAMGUxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xJDAiBgNV
# BAMTG0RpZ2lDZXJ0IEFzc3VyZWQgSUQgUm9vdCBDQTAeFw0yMjA4MDEwMDAwMDBa
# Fw0zMTExMDkyMzU5NTlaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2Vy
# dCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lD
# ZXJ0IFRydXN0ZWQgUm9vdCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
# ggIBAL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3E
# MB/zG6Q4FutWxpdtHauyefLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKy
# unWZanMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsF
# xl7sWxq868nPzaw0QF+xembud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU1
# 5zHL2pNe3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJB
# MtfbBHMqbpEBfCFM1LyuGwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObUR
# WBf3JFxGj2T3wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6
# nj3cAORFJYm2mkQZK37AlLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxB
# YKqxYxhElRp2Yn72gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5S
# UUd0viastkF13nqsX40/ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+x
# q4aLT8LWRV+dIPyhHsXAj6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjggE6MIIB
# NjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTs1+OC0nFdZEzfLmc/57qYrhwP
# TzAfBgNVHSMEGDAWgBRF66Kv9JLLgjEtUYunpyGd823IDzAOBgNVHQ8BAf8EBAMC
# AYYweQYIKwYBBQUHAQEEbTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdp
# Y2VydC5jb20wQwYIKwYBBQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNv
# bS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcnQwRQYDVR0fBD4wPDA6oDigNoY0
# aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENB
# LmNybDARBgNVHSAECjAIMAYGBFUdIAAwDQYJKoZIhvcNAQEMBQADggEBAHCgv0Nc
# Vec4X6CjdBs9thbX979XB72arKGHLOyFXqkauyL4hxppVCLtpIh3bb0aFPQTSnov
# Lbc47/T/gLn4offyct4kvFIDyE7QKt76LVbP+fT3rDB6mouyXtTP0UNEm0Mh65Zy
# oUi0mcudT6cGAxN3J0TU53/oWajwvy8LpunyNDzs9wPHh6jSTEAZNUZqaVSwuKFW
# juyk1T3osdz9HNj0d1pcVIxv76FQPfx2CWiEn2/K2yCNNWAcAgPLILCsWKAOQGPF
# mCLBsln1VWvPJ6tsds5vIy30fnFqI2si/xK4VC0nftg62fC2h5b9W9FcrBjDTZ9z
# twGpn1eqXijiuZQwggZdMIIERaADAgECAhBpTFLXctn5PbJa0As3IGxtMA0GCSqG
# SIb3DQEBCwUAMFYxCzAJBgNVBAYTAlBMMSEwHwYDVQQKExhBc3NlY28gRGF0YSBT
# eXN0ZW1zIFMuQS4xJDAiBgNVBAMTG0NlcnR1bSBDb2RlIFNpZ25pbmcgMjAyMSBD
# QTAeFw0yNjEwMDUxMzMxNDFaFw0yNzEwMDUxMzMxNDBaMIGCMQswCQYDVQQGEwJV
# UzESMBAGA1UECAwJV2lzY29uc2luMRIwEAYDVQQHDAlHcmVlbiBCYXkxHjAcBgNV
# BAoMFU9wZW4gU291cmNlIERldmVsb3BlcjErMCkGA1UEAwwiT3BlbiBTb3VyY2Ug
# RGV2ZWxvcGVyIERhbmllbCBEYW1pdDCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCC
# AYoCggGBANilePw/amtPJjQeEn4JFolWXMyIqYt6qWyV8w8x1UxEay+xJ4AXUZOZ
# x1fqS+H/rHVwW2Qt1Z2yYmYxaq5HHCUXz3KfjsvCamr7VVgytzmkJYid9ciQsZNQ
# 5ki3cwp63NUm6TsuUUln/9AzTfRDFVFQYZJWj6gSyzg8VMzd8J67YgZsb9b/gjWW
# hnP6IdHhSEYvINMKDVd4R0KCsSKPspArt5g/c/MkmqbKNa73zHfhTbJWPG+azmIN
# oEfFt8aUOp98+jsi3o6nI/vH7kT4HMm6HZrTwGPpkkWF6Y8aazCcaYP6e3skwYF6
# NNv6lbNXGNpTZZrta1kqHPaXfyK+QgjYUK2VxXivV2LuhfaeLeyq1ex2dty2U4Si
# e6zeJqihKYxDEcwUIburAZ9ei8qKugbmT0Rp9Hhn8GUl+TeJfSebnB/CpGfwU6A4
# k7MsYRBGOcpnaHAxYPLsIO+TRPjAzLU6aPSjMmMq76Mc5/vP7qJOhYcMZy5KQA5E
# QmyC7e41JQIDAQABo4IBeDCCAXQwDAYDVR0TAQH/BAIwADA9BgNVHR8ENjA0MDKg
# MKAuhixodHRwOi8vY2NzY2EyMDIxLmNybC5jZXJ0dW0ucGwvY2NzY2EyMDIxLmNy
# bDBzBggrBgEFBQcBAQRnMGUwLAYIKwYBBQUHMAGGIGh0dHA6Ly9jY3NjYTIwMjEu
# b2NzcC1jZXJ0dW0uY29tMDUGCCsGAQUFBzAChilodHRwOi8vcmVwb3NpdG9yeS5j
# ZXJ0dW0ucGwvY2NzY2EyMDIxLmNlcjAfBgNVHSMEGDAWgBTddF1MANt7n6B0yrFu
# 9zzAMsBwzTAdBgNVHQ4EFgQUXEW08OGC/PMxgp4+sfHWDuO+VlAwSwYDVR0gBEQw
# QjAIBgZngQwBBAEwNgYLKoRoAYb2dwIFAQQwJzAlBggrBgEFBQcCARYZaHR0cHM6
# Ly93d3cuY2VydHVtLnBsL0NQUzATBgNVHSUEDDAKBggrBgEFBQcDAzAOBgNVHQ8B
# Af8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBACmDxwDt3CyhNLBL/Hgcn9cnYkJa
# rOYB95K1G38KJGWxyH0ABL7+VhmG3dUsw0M3CldokOOsYglSXMBnXoDUwjbtafEH
# JJf5XkGyllKIVKVy3i2vvrdaW3GZW3aJ8h/iqPbcG3T4/ghQMxsQXvVc9JjQ0V+l
# IHIJnYDSZlcmCqVhUglgRCtV3X4Z5QaTXh+bDWz2UgP8Rh8X0vfr24e//AmoAMAm
# wsjBJh6f+VR+bcjoYZz8goqxbc14tEROzybiwcuxty46E35OaMDQbf0niBUhRsFI
# cgZ9Yc3EtENQpl539qE/G12uvVJdLN5+YGU5Eq2j3Pvi0ULEueWPHAl5BtsxL72l
# JW6ET4AWVs1GD3cS6lYXlQQfIgv3vpjry5VS3G7j2IsqjGpoz1ICFAyjpHxxdiXD
# XmIMQfPco7I5FJIZaJblehUY1Y5B7wJk7X3W822hVyi0/q3qWiJu/DENsivpC6ds
# pl/l544af0OEusv1HslZcJ7cL0hJojqaYbn21Rhp5C9pAuI7s36PbdSpXw/dIbNr
# 4QxOsA2EYBwcgYWF4wczdbsJg3KpnriFUs/dVGcYFbhqdhtPWSiXg/CyFQjdpnHS
# TsLMjqO137madchLsRR4NktGTjEiFiq4WYm9df9UImQKP1otePSdpMLjItHn/Ln/
# uzy3ZnU96zwlheYwMIIGtDCCBJygAwIBAgIQDcesVwX/IZkuQEMiDDpJhjANBgkq
# hkiG9w0BAQsFADBiMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5j
# MRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBU
# cnVzdGVkIFJvb3QgRzQwHhcNMjUwNTA3MDAwMDAwWhcNMzgwMTE0MjM1OTU5WjBp
# MQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMT
# OERpZ2lDZXJ0IFRydXN0ZWQgRzQgVGltZVN0YW1waW5nIFJTQTQwOTYgU0hBMjU2
# IDIwMjUgQ0ExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtHgx0wqY
# QXK+PEbAHKx126NGaHS0URedTa2NDZS1mZaDLFTtQ2oRjzUXMmxCqvkbsDpz4aH+
# qbxeLho8I6jY3xL1IusLopuW2qftJYJaDNs1+JH7Z+QdSKWM06qchUP+AbdJgMQB
# 3h2DZ0Mal5kYp77jYMVQXSZH++0trj6Ao+xh/AS7sQRuQL37QXbDhAktVJMQbzIB
# HYJBYgzWIjk8eDrYhXDEpKk7RdoX0M980EpLtlrNyHw0Xm+nt5pnYJU3Gmq6bNMI
# 1I7Gb5IBZK4ivbVCiZv7PNBYqHEpNVWC2ZQ8BbfnFRQVESYOszFI2Wv82wnJRfN2
# 0VRS3hpLgIR4hjzL0hpoYGk81coWJ+KdPvMvaB0WkE/2qHxJ0ucS638ZxqU14lDn
# ki7CcoKCz6eum5A19WZQHkqUJfdkDjHkccpL6uoG8pbF0LJAQQZxst7VvwDDjAmS
# FTUms+wV/FbWBqi7fTJnjq3hj0XbQcd8hjj/q8d6ylgxCZSKi17yVp2NL+cnT6To
# y+rN+nM8M7LnLqCrO2JP3oW//1sfuZDKiDEb1AQ8es9Xr/u6bDTnYCTKIsDq1Btm
# XUqEG1NqzJKS4kOmxkYp2WyODi7vQTCBZtVFJfVZ3j7OgWmnhFr4yUozZtqgPrHR
# VHhGNKlYzyjlroPxul+bgIspzOwbtmsgY1MCAwEAAaOCAV0wggFZMBIGA1UdEwEB
# /wQIMAYBAf8CAQAwHQYDVR0OBBYEFO9vU0rp5AZ8esrikFb2L9RJ7MtOMB8GA1Ud
# IwQYMBaAFOzX44LScV1kTN8uZz/nupiuHA9PMA4GA1UdDwEB/wQEAwIBhjATBgNV
# HSUEDDAKBggrBgEFBQcDCDB3BggrBgEFBQcBAQRrMGkwJAYIKwYBBQUHMAGGGGh0
# dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBBBggrBgEFBQcwAoY1aHR0cDovL2NhY2Vy
# dHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcnQwQwYDVR0f
# BDwwOjA4oDagNIYyaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1
# c3RlZFJvb3RHNC5jcmwwIAYDVR0gBBkwFzAIBgZngQwBBAIwCwYJYIZIAYb9bAcB
# MA0GCSqGSIb3DQEBCwUAA4ICAQAXzvsWgBz+Bz0RdnEwvb4LyLU0pn/N0IfFiBow
# f0/Dm1wGc/Do7oVMY2mhXZXjDNJQa8j00DNqhCT3t+s8G0iP5kvN2n7Jd2E4/iEI
# UBO41P5F448rSYJ59Ib61eoalhnd6ywFLerycvZTAz40y8S4F3/a+Z1jEMK/DMm/
# axFSgoR8n6c3nuZB9BfBwAQYK9FHaoq2e26MHvVY9gCDA/JYsq7pGdogP8HRtrYf
# ctSLANEBfHU16r3J05qX3kId+ZOczgj5kjatVB+NdADVZKON/gnZruMvNYY2o1f4
# MXRJDMdTSlOLh0HCn2cQLwQCqjFbqrXuvTPSegOOzr4EWj7PtspIHBldNE2K9i69
# 7cvaiIo2p61Ed2p8xMJb82Yosn0z4y25xUbI7GIN/TpVfHIqQ6Ku/qjTY6hc3hsX
# MrS+U0yy+GWqAXam4ToWd2UQ1KYT70kZjE4YtL8Pbzg0c1ugMZyZZd/BdHLiRu7h
# AWE6bTEm4XYRkA6Tl4KSFLFk43esaUeqGkH/wyW4N7OigizwJWeukcyIPbAvjSab
# nf7+Pu0VrFgoiovRDiyx3zEdmcif/sYQsfch28bZeUz2rtY/9TCA6TD8dC3JE3rY
# krhLULy7Dc90G6e8BlqmyIjlgp2+VqsS9/wQD7yFylIz0scmbKvFoW2jNrbM1pD2
# T7m3XDCCBrkwggShoAMCAQICEQCZo4AKJlU7ZavcboSms+o5MA0GCSqGSIb3DQEB
# DAUAMIGAMQswCQYDVQQGEwJQTDEiMCAGA1UEChMZVW5pemV0byBUZWNobm9sb2dp
# ZXMgUy5BLjEnMCUGA1UECxMeQ2VydHVtIENlcnRpZmljYXRpb24gQXV0aG9yaXR5
# MSQwIgYDVQQDExtDZXJ0dW0gVHJ1c3RlZCBOZXR3b3JrIENBIDIwHhcNMjEwNTE5
# MDUzMjE4WhcNMzYwNTE4MDUzMjE4WjBWMQswCQYDVQQGEwJQTDEhMB8GA1UEChMY
# QXNzZWNvIERhdGEgU3lzdGVtcyBTLkEuMSQwIgYDVQQDExtDZXJ0dW0gQ29kZSBT
# aWduaW5nIDIwMjEgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCd
# I88EMCM7wUYs5zNzPmNdenW6vlxNur3rLfi+5OZ+U3iZIB+AspO+CC/bj+taJUbM
# bFP1gQBJUzDUCPx7BNLgid1TyztVLn52NKgxxu8gpyTr6EjWyGzKU/gnIu+bHAse
# 1LCitX3CaOE13rbuHbtrxF2tPU8f253QgX6eO8yTbGps1Mg+yda3DcTsOYOhSYNC
# JiL+5wnjZ9weoGRtvFgMHtJg6i671OPXIciiHO4Lwo2p9xh/tnj+JmCQEn5QU0Nx
# zrOiRna4kjFaA9ZcwSaG7WAxeC/xoZSxF1oK1UPZtKVt+yrsGKqWONoK6f5EmBOA
# VEK2y4ATDSkb34UD7JA32f+Rm0wsr5ajzftDhA5mBipVZDjHpwzv8bTKzCDUSUuU
# mPo1govD0RwFcTtMXcfJtm1i+P2UNXadPyYVKRxKQATHN3imsfBiNRdN5kiVVeqP
# 55piqgxOkyt+HkwIA4gbmSc3hD8ke66t9MjlcNg73rZZlrLHsAIV/nJ0mmgSjBI/
# TthoGJDydekOQ2tQD2Dup/+sKQptalDlui59SerVSJg8gAeV7N/ia4mrGoiez+Sq
# V3olVfxyLFt3o/OQOnBmjhKUANoKLYlKmUpKEFI0PfoT8Q1W/y6s9LTI6ekbi0ig
# EbFUIBE8KDUGfIwnisEkBw5KcBZ3XwnHmfznwlKo8QIDAQABo4IBVTCCAVEwDwYD
# VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU3XRdTADbe5+gdMqxbvc8wDLAcM0wHwYD
# VR0jBBgwFoAUtqFUOQLDoD+Oirz61PgcptE6Dv0wDgYDVR0PAQH/BAQDAgEGMBMG
# A1UdJQQMMAoGCCsGAQUFBwMDMDAGA1UdHwQpMCcwJaAjoCGGH2h0dHA6Ly9jcmwu
# Y2VydHVtLnBsL2N0bmNhMi5jcmwwbAYIKwYBBQUHAQEEYDBeMCgGCCsGAQUFBzAB
# hhxodHRwOi8vc3ViY2Eub2NzcC1jZXJ0dW0uY29tMDIGCCsGAQUFBzAChiZodHRw
# Oi8vcmVwb3NpdG9yeS5jZXJ0dW0ucGwvY3RuY2EyLmNlcjA5BgNVHSAEMjAwMC4G
# BFUdIAAwJjAkBggrBgEFBQcCARYYaHR0cDovL3d3dy5jZXJ0dW0ucGwvQ1BTMA0G
# CSqGSIb3DQEBDAUAA4ICAQB1iFgP5Y9QKJpTnxDsQ/z0O23JmoZifZdEOEmQvo/7
# 9PQg9nLF/GJe6ZiUBEyDBHMtFRK0mXj3Qv3gL0sYXe+PPMfwmreJHvgFGWQ7Xwnf
# Mh2YIpBrkvJnjwh8gIlNlUl4KENTK5DLqsYPEtRQCw7R6p4s2EtWyDDr/M58iY2U
# BEqfUU/ujR9NuPyKk0bEcEi62JGxauFYzZ/yld13fHaZskIoq2XazjaD0pQkcQiI
# ueL0HKiohS6XgZuUtCKA7S6CHttZEsObQJ1j2s0urIDdqF7xaXFVaTHKtAuMfwi0
# jXtF3JJphrJfc+FFILgCbX/uYBPBlbBIP4Ht4xxk2GmfzMn7oxPITpigQFJFWuzT
# MUUgdRHTxaTSKRJ/6Uh7ki/pFjf9sUASWgxT69QF9Ki4JF5nBIujxZ2sOU9e1HSC
# JwOfK07t5nnzbs1LbHuAIGJsRJiQ6HX/DW1XFOlXY1rc9HufFhWU+7Uk+hFkJsfz
# qBz3pRO+5aI6u5abI4Qws4YaeJH7H7M8X/YNoaArZbV4Ql+jarKsE0+8XvC4DJB+
# IVcvC9Ydqahi09mjQse4fxfef0L7E3hho2O3bLDM6v60rIRUCi2fJT2/IRU5ohgy
# Tch4GuYWefSBsp5NPJh4QRTP9DC3gc5QEKtbrTY0Ka87Web7/zScvLmvQBm8JDFp
# DjCCBu0wggTVoAMCAQICEAhP3DNPfkVO28MPj/mSGDUwDQYJKoZIhvcNAQELBQAw
# aTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMUEwPwYDVQQD
# EzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGluZyBSU0E0MDk2IFNIQTI1
# NiAyMDI1IENBMTAeFw0yNjA4MDUwMDAwMDBaFw0zNzExMDQyMzU5NTlaMGMxCzAJ
# BgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjE7MDkGA1UEAxMyRGln
# aUNlcnQgU0hBMjU2IFJTQTQwOTYgVGltZXN0YW1wIFJlc3BvbmRlciAyMDI2IDEw
# ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC2e6byyf7NSvjUm0xls/04
# xjD4fAkOkbnGQi7+Wpx81iYxfzViaxSIctuH3KSl5YEYpMuFgGsA31N2D9ATMbfZ
# dw5uaAhuWevQKhDdZIB4NnqcfpfpWQXJiQnDdAElETC+bhSEvNLGbA8DtwUpFMQ4
# yyYQSPqomT92osQAv6hBi47ATZS6JfVWe6XxhF4jJZ3iSAuf2Cros1czRSmWRHqM
# v9AfGZvp8ygYElhudpQjtcPpwoOl6QrZJUyV3iINvN4cO05prGV0fkjG426xDr2d
# 3z9lcSIHkdvGPdGUrXdxfVbgOUVcp2/8ISEzwKPW++Wa+E2ujI91EZtukGWDJ/xZ
# 27k3oHKEXBRGfRTqjOU+jE3ba/5++JSE/7oNHnjs5mekExYN96LV/mxUbCKJb8pB
# NY4r3uD7hEmk/M81XhVgwDA7aMzYC3LZBg9WY5BMmbSay5ecmtJuXaB/0nKWmQmV
# ZeqTVDgsmzHP5MQuhAJkiWNuC9MmCg9TZHXbJ2/yLVSov9p16UDTLtT0+aa1vN71
# fHeu1qMLlLNB3WOB/ADCxr3S/1hxI92Z6jKgEED/btwIvbfuXkNNhg8MtDg43c4t
# MZae9FvqMOt/9PvmAxF9TNIsIFB8G6yb36ZJZGUL8N/pL971DyLXcK6HM5PYnH5X
# +eVtczhCgHCVQCF6XDAlPQIDAQABo4IBlTCCAZEwDAYDVR0TAQH/BAIwADAdBgNV
# HQ4EFgQUFMljijAu1Er7bpTz5uNAfvXszeIwHwYDVR0jBBgwFoAU729TSunkBnx6
# yuKQVvYv1Ensy04wDgYDVR0PAQH/BAQDAgeAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMIGVBggrBgEFBQcBAQSBiDCBhTAkBggrBgEFBQcwAYYYaHR0cDovL29jc3Au
# ZGlnaWNlcnQuY29tMF0GCCsGAQUFBzAChlFodHRwOi8vY2FjZXJ0cy5kaWdpY2Vy
# dC5jb20vRGlnaUNlcnRUcnVzdGVkRzRUaW1lU3RhbXBpbmdSU0E0MDk2U0hBMjU2
# MjAyNUNBMS5jcnQwXwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL2NybDMuZGlnaWNl
# cnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZEc0VGltZVN0YW1waW5nUlNBNDA5NlNIQTI1
# NjIwMjVDQTEuY3JsMCAGA1UdIAQZMBcwCAYGZ4EMAQQCMAsGCWCGSAGG/WwHATAN
# BgkqhkiG9w0BAQsFAAOCAgEAjcU6YR6dUgrfmawJgH59KECxa9Ji8sEi2g10CBDa
# MiqsaxWyW5cwlT/6ZF5sFznazqVsoC85U9dqLOYqQwst+UQQoNlDHgKRLa3xoc+O
# ReFreFhnTXSG0Vrd2E2CZqUfm+5a+He1MJ/h+tNLuA+0Zzhn/Fo+FDYAHWZHx4R7
# 9ZsfRFYe9UiXpXBDf6DkUo183Y38NYmR/XfDYf7YZ+oR9t3flbDwK+hgGMs0gNNp
# 1w9Z2CyOyI5or/sSwomAuNQ0hWC9xoU4stD8aWsD7RkcmgVRs6vlIk3zPKQ+ylch
# eWkMlj+CoVRlFE55pv0ZWCaFt04lwP/rdGHE9qEVQZtyRE42ox7oNgC/r+Y4bSlZ
# 3dw9K2x1xLtu6PkPKeLBFjzKigwfqm3Hm+k/+lnME8F5kPZTgiy2HLEHklpryqs6
# QHnPXrRNeIzkAMyylnRN8P0wmirS0WkU+ywpEWFZ4QNg+9xS43tTuW9x0eXh7NDc
# 1P/sV+zWxHXKH8tFt1ncHdVzqrZaYPyYMLSn2TOXajveJW1L3joiQSPsWRGxkbDD
# W15jERFE4LvjnGu2O9zD1nLJSMdlYZEikl4w2w+q4IN/R+TIe0H4ngCI1moJCTbe
# vGH4punIxM1Uoi0nmX3ZK+XbRT01uowE5ViXWHng0RgsmrX/EdYUo80r3TfMlkD0
# /YMxggXGMIIFwgIBATBqMFYxCzAJBgNVBAYTAlBMMSEwHwYDVQQKExhBc3NlY28g
# RGF0YSBTeXN0ZW1zIFMuQS4xJDAiBgNVBAMTG0NlcnR1bSBDb2RlIFNpZ25pbmcg
# MjAyMSBDQQIQaUxS13LZ+T2yWtALNyBsbTANBglghkgBZQMEAgEFAKCBhDAYBgor
# BgEEAYI3AgEMMQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEE
# MBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEiBCAR
# /rhLd3TmHpeoX4fO9Tg82Qld4fjUR32whjNpa34HUTANBgkqhkiG9w0BAQEFAASC
# AYBGhoUOU3TLshwEvImiiiqY2OhqNfxn8IrED2o+NYhcnFCE6tJODgr1+PkycK06
# 2UvuVEMh1hpJ/WM2AwnJh0qnNNKJ105yNc1tWM1mlZ3fBWI9OJlF+lm1EyrpWdIl
# 4C9riq0zgxN2tg0qNM2fHqcTm9cL1+mXlTfSqPkmvuFDehBOQHT2FADP6KHK+bVR
# fVg/zReQOANLFViwyz9fyIV2Qvc+lB7wHdrHhb2QppfD9tIluWM7q6b6qPw0zpGs
# 4GzbfXhj/7tzxuPAmcHy9sXStn53WbIlaJ2PK1opJyv87Ztp01IurUnUnlANJl7Y
# eJ7SJXfCSI2KTbAsQA8QWhNT3XpVU1iOLdNBMsrWQAe8BB40N8wIjIBaLqxRe2J7
# Rr5lFunzS05Vn3MvTcAUZJLlWvkCTWY+2OO9Z75dVS5cXswYR8p1oe/ZPI3yioD+
# 0rNpomAiJ54JE1u70ZRx8A5P9GvIorxgg5/1S4XVl/J8tzBFNg+My10ThmhB/A53
# O4qhggMmMIIDIgYJKoZIhvcNAQkGMYIDEzCCAw8CAQEwfTBpMQswCQYDVQQGEwJV
# UzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRy
# dXN0ZWQgRzQgVGltZVN0YW1waW5nIFJTQTQwOTYgU0hBMjU2IDIwMjUgQ0ExAhAI
# T9wzT35FTtvDD4/5khg1MA0GCWCGSAFlAwQCAQUAoGkwGAYJKoZIhvcNAQkDMQsG
# CSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjYxMDA1MTYyNzE4WjAvBgkqhkiG
# 9w0BCQQxIgQgBfHNWiFLhSZ+YegnZJ8pqzbTMTJsFebs73gNsttNYBgwDQYJKoZI
# hvcNAQEBBQAEggIANQncH0OwdjaRZtg6bIGeh9spG0mSDUaX1M/0h6y2fMHEJ5JF
# nMzzdrD0DaaweJRMyX7fmGzv82OEEJpcnpVd8IqRhc3WQScfTraJBlP0plKblnpV
# 1nWLkvgM7P8OjQ5DkxDdKwicElGpny6EbA4ZORBQemfyU7cr7IcF6mhEwdYY1NpW
# wdC/N4fQt93p1b2SzcA/GQZccN1Y+XcKVlVdbgNgbROCHx3/qr/+L9rYkoBhZT7F
# /sbmBG4zm7RcZki4Pp8KjyfnJ4MBuZ6qLhdfRd/JjuEjYRbcxviaXZ21m/lEO39p
# P8oAlVYcnb/2seU6Bq3GB28ruBrrKYZC6fGcBx5nZ0CeZ7UMzTTm5DiMr3ijYRf6
# XNDKH/JVtAvK+XLrK4iwajfPW8viXbXG/apl4WPHsflBuH4qy7jwfqEz7PF1WioP
# vbx5dXoy1mCbYt+PFp6TDQUiMttG2e+jX1ofj4Uu3yBopuxx7/BgJ+PrDFlErYDT
# CrjyAMgjm0THLbcwjnYY8eO3OEpdb4IEtsqaWfRXF2Z/SDaZoqsP+dGmCQFTy/LJ
# 7CuCs8KpvKjtw+cMP5JkIi9EsqyVe5vne8HmtiL9aNmidAfWaLKZZqBDquJZ1Nv4
# I0qt4DkQ8L5fWoePWLeZhFdV6RbSwHKoClW+/062+ZghfnCN7ym00/Ad0GA=
# SIG # End signature block
